//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace harley.bd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HarleyEntities6 : DbContext
    {
        public HarleyEntities6()
            : base("name=HarleyEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<histori> histori { get; set; }
        public virtual DbSet<login_data> login_data { get; set; }
        public virtual DbSet<motor> motor { get; set; }
        public virtual DbSet<ocom> ocom { get; set; }
        public virtual DbSet<otzov3> otzov3 { get; set; }
        public virtual DbSet<spotster> spotster { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<division> division { get; set; }
    }
}
