//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace harley.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class otzov3
    {
        public int id { get; set; }
        public string name { get; set; }
        public string motor { get; set; }
        public string mot { get; set; }
        public string otzov2 { get; set; }
        public string otzov5 { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idMotor { get; set; }
        public Nullable<int> idSpotster { get; set; }
        public Nullable<int> idComp { get; set; }
    
        public virtual login_data login_data { get; set; }
        public virtual motor motor1 { get; set; }
        public virtual ocom ocom { get; set; }
        public virtual spotster spotster { get; set; }
    }
}
