//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace harley.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class spotster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public spotster()
        {
            this.otzov3 = new HashSet<otzov3>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public Nullable<int> division { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<otzov3> otzov3 { get; set; }
        public virtual division division1 { get; set; }
    }
}
